// JS Web/React JS Fundamentals/final project/front-end/src/views/All/All.jsx
import React, { Component } from 'react'
import Sidebar from '../../components/Sidebar';
import {NavLink} from 'react-router-dom'

class AllPosts extends Component {
    constructor(props) {
        super(props);
        this.state = {
        };
    }
    render() {
        return (
            <section className="site-section pt-5">
                <div className="container">
                    <div className="row blog-entries">
                        <div className="col-md-12 col-lg-8 main-content">
                            <div className="col-md-12 mb-5">
                                <h2>All Posts</h2>
                            </div>
                            {this.props.posts.map(p=> (
                                <div key ={p._id} className="col-md-12">
                                    <div className="post-entry-horzontal">
                                        <NavLink to={"/posts/" + p._id}>
                                            <div className="image" style={{ backgroundImage: `url(${p.imageUrl})` }} />
                                            <span className="text">
                                                <div className="post-meta">
                                                    <span className="author mr-2"><img src="images/atanas-yonkov.jpg" alt="pic placeholder" /> {p.author.username}</span>•
                                                    <span className="mr-2">{p.creationDate} </span> •
                                                </div>
                                                <h2>{p.title}</h2>
                                            </span>
                                        </NavLink>
                                    </div>
                                {/* END post */}
                                
                                </div>

                            ))}
                        </div>
                        <Sidebar posts={this.props.posts} handleChange={this.props.handleChange} />
                    </div>
                </div>
            </section>
        )

    }
}

export default AllPosts;

// JS Web/Angular JS Fundamentals/final-project/src/app/blog/all/all.component.ts
import { Component, OnInit } from '@angular/core';
import { Post } from 'src/app/models/post';
import { Observable } from 'rxjs';
import { BlogService } from '../blog.service';

@Component({
  selector: 'app-furniture-all',
  templateUrl: './all.component.html',
  styleUrls: ['./all.component.css']
})
export class AllComponent implements OnInit {
  posts$: Observable<Array<Post>>;
  constructor(private postService: BlogService) { }

  ngOnInit() {
    this.posts$ = this.postService.getAllPost()
  }

}

<section class="site-section pt-5">
  <div class="container">
    <div class="row blog-entries">
      <div class="col-md-12 col-lg-10 main-content">
        <div class="col-md-12 mb-5">
          <h2>All Posts</h2>
        </div>
        <div class="col-md-12" *ngFor="let p of posts$ | async">
          <div class="post-entry-horzontal">
            <a [routerLink]="['/blog/details', p._id]">
              <img src="{{p.image}}" />
              <span class="text">
                <div class="post-meta">
                  <span class="author mr-2"><img src="/assets/images/atanas-yonkov.jpg" alt="pic placeholder" />
                    Admin</span>•
                  <span class="mr-2">{{p.creationDate | date: 'MMMM/dd/yyyy'}} </span>
                </div>
                <h2 class="title">{{p.title}}</h2>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
