// JS Web/Angular JS Fundamentals/final-project/front-end/src/app/components/navigation/navigation.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.css']
})
export class NavigationComponent implements OnInit {
  constructor(
    public authService: AuthService,
    private router: Router
  ) {  }

  ngOnInit() {
  }

  logout() {
    this.authService.logout();
    
    this.router.navigate([ '/signin' ]);
  }
}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <img class="angular-logo" src="https://angular.io/assets/images/logos/angular/angular.svg"/>
  <a class="navbar-brand" routerLink="/">Angular Blog</a>
  <button appCollapse class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor01"
    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li *ngIf="!authService.isAuthenticated()" class="nav-item">
        <a class="nav-link" routerLink="/signin">Sign In</a>
      </li>
      <li *ngIf="!authService.isAuthenticated()" class="nav-item">
        <a class="nav-link" routerLink="/signup">Sign Up</a>
      </li>
      <li *ngIf="authService.isAuthenticated()" class="nav-item">
        <a class="nav-link" (click)="logout()">Logout</a>
      </li>
      <li appNavDropdown class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">Blog</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a *ngIf="authService.isAdmin()" class="dropdown-item" routerLink="/blog/create">Create</a>
            <a class="dropdown-item" routerLink="/blog/about">About</a>
          <a class="dropdown-item" routerLink="/blog/all">All Posts</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

// JS Web/React JS Fundamentals/final project/front-end/src/components/Navigation.jsx
import React, { Component } from 'react';
import { NavLink } from 'react-router-dom';

class Navigation extends Component {
  constructor(props) {
    super(props);
    this.toggleNavbar = this.toggleNavbar.bind(this);
    this.state = {
      collapsed: true,
    };
  }
  toggleNavbar() {
    this.setState({
      collapsed: !this.state.collapsed,
    });
  }
  render() {
    const { isAdmin, isAuthed, logout } = this.props;
    const collapsed = this.state.collapsed;
    const classOne = collapsed ? 'collapse navbar-collapse' : 'collapse navbar-collapse show';
    const classTwo = collapsed ? 'navbar-toggler navbar-toggler-right collapsed' : 'navbar-toggler navbar-toggler-right';
    return (
      <nav className="navbar navbar-expand-lg navbar-light bg-light nav">
        <div className="container">
          <button onClick={this.toggleNavbar} className={`${classTwo}`} type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon" />
          </button>
          <div className={`${classOne}`} id="navbarResponsive">
            <ul className="navbar-nav mx-auto">
              <li className="nav-item">

                <NavLink exact className="nav-link" to="/">Home</NavLink>
              </li>
              <li className="nav-item">
                {!isAuthed && <NavLink className="nav-link" to="/login">Login</NavLink>}
              </li>
              <li className="nav-item">
                {!isAuthed && <NavLink className="nav-link" to="/register">Register</NavLink>}
              </li>
              <li className="nav-item">
                {isAuthed && <NavLink className="nav-link" to="/logout" onClick={logout}>Logout</NavLink>}
              </li>
              <li className="nav-item">
                {isAdmin && <NavLink className="nav-link" to="/create">Create</NavLink>}
              </li>
              <li className="nav-item">
                <NavLink className="nav-link" to="/about">About</NavLink>
              </li>
              <li className="nav-item">
                <NavLink className="nav-link" to="/all">All Posts</NavLink>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    );
  }
}
export default Navigation;
