// JS Web/React JS Fundamentals/final project/front-end/src/views/Details/Details.jsx
import React, { Component } from 'react';
import Sidebar from '../../components/Sidebar';
import { NavLink } from 'react-router-dom'
import ReactHtmlParser, { processNodes, convertNodeToElement, htmlparser2 } from 'react-html-parser';

class Details extends Component {
  constructor(props) {
    super(props);
    this.state = {
      post: null,
      comment: null
    }
    this.handleChange = props.handleChange.bind(this);
  }

  componentDidMount() {
    const { posts, match } = this.props;

    this.setState({
      post: posts.length
        ? posts.find(p => p._id === match.params.id)
        : null,
      userId: localStorage.getItem('userId')
    })
  }

  componentDidUpdate(prevProps) {
    const { posts, match, isAuthed } = this.props;

    if (JSON.stringify(prevProps) === JSON.stringify(this.props)) {
      return;
    }

    this.setState({
      post: posts.length
        ? posts.find(p => p._id === match.params.id)
        : null
    });
    console.log(this.state.post)
  }

  render() {
    const { post } = this.state;
    const { isAdmin, isAuthed } = this.props;
console.log(isAuthed);

    if (!post) {
      return <span>Loading post ...</span>;
    }

    return (
      <section className="site-section py-lg">
        <div className="container">
          <div className="row blog-entries">
            <div className="col-md-12 col-lg-8 main-content">
              <img src={post.imageUrl} alt="image placeholder" className="img-fluid mb-5" />
              <div className="post-meta">
                <span className="author mr-2"><img src="/images/atanas-yonkov.jpg" alt="pic" className="mr-2" />{post.author.username}</span>•
              <span className="mr-2">{this.props.formatDate(post.creationDate)} </span> •
              <span className="ml-2"><span className="fa fa-comments" /> 3</span>
              </div>
              {isAdmin && <NavLink to={isAdmin && "/edit/" + this.props.match.params.id}>edit post </NavLink>}
              {isAdmin && <NavLink to={"/delete/" + this.props.match.params.id}>delete post</NavLink>}
              <h1 className="mb-4">{post.title}</h1>
              <div className="post-content-body">
                <div className="row mb-5">
                </div>
                {ReactHtmlParser(post.content)}
              </div>
              <div className="pt-5">
                <h3 className="mb-5">Comments</h3>
                <ul className="comment-list">
                {post.comments.map(comment =>
                  <li className="comment">
                  <div className="vcard">
                    <img src="/images/person_1.jpg" alt="Image placeholder" />
                  </div>
                  <div className="comment-body">
                     <h3>{comment.author.username}</h3>
                     <div className="meta">{this.props.formatDate(comment.creationDate)}</div>
                     <p>{comment.comment}</p>
                     <p><a href="#" className="reply rounded">Reply</a></p>
                   </div>
                 </li>
                
                  )}
                  
                </ul>
                {/* END comment-list */}
                <div className="comment-form-wrap pt-5">
                  {isAuthed ? <h3 className="mb-5">Leave a comment</h3> 
                  : 
                  <h3 className="mb-5">Please log in or register to post a comment</h3> }
                  {isAuthed && <form onSubmit={(e) => this.props.handleSubmit(e, this.state)} className="p-5 bg-light">

                    <div className="form-group">
                      <label htmlFor="message">Message</label>
                      <textarea name="comment" id="message" onChange={this.handleChange} cols={30} rows={10} className="form-control" defaultValue={""} />
                    </div>
                    <div className="form-group">
                      <input type="submit" defaultValue="Post Comment" className="btn btn-primary" />
                    </div>
                  </form>}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>



    );
  }
}

export default Details;

// JS Web/Angular JS Fundamentals/final-project/front-end/src/app/components/blog/details/details.component.ts
import { Component, OnInit, OnChanges } from '@angular/core';
import { Post } from '../../../shared/models/post';
import { ActivatedRoute } from '@angular/router';
import { BlogService } from '../../../core/services/blog.service';
import { AuthService } from '../../../core/services/auth.service';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';

@Component({
  selector: 'app-details',
  templateUrl: './details.component.html',
  styleUrls: ['./details.component.css']
})
export class DetailsComponent implements OnInit {
  post: Post;
  form: FormGroup
  constructor(
    private route: ActivatedRoute,
    public authService: AuthService,
    public postService: BlogService,
    private fb: FormBuilder
  ) { }

  ngOnInit() {
    this.post = this.route.snapshot.data['post'];
    
    this.form = this.fb.group({
      comment: ['', [Validators.required]]
    })
  }
  createComment() {
    this.route.params.subscribe(data => {
      const id = data['id']
      this.form.value.id=id;
      this.postService.createComment(this.form.value).subscribe((data) => {
          setTimeout(() => {
            this.postService.getPost(id).subscribe(data => {
              this.post = data;
            });
          }, 700);
          
            this.form.reset();
        });
        
      
    });
  }



  get f() { return this.form.controls }

  get invalid() { return this.form.invalid }

}
<div class="container">
  <div class="row space-top">
    <div class="col-md-9">
      <h1>Post Details</h1>
    </div>
  </div>
  <div class="row space-top">
    <div class="col-md-9">
      <div class="card text-white bg-primary">
        <div class="card-body">
          <blockquote class="card-blockquote">
            <img class="featured-image" src="{{post.image}}" />
          </blockquote>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="admin-content" *ngIf="authService.isAdmin()">
        <a [routerLink]="['/blog/edit', post.id]" class="">Edit Post </a>
        <a [routerLink]="['/blog/delete', post.id]" class="">Delete Post</a>
      </div>
      <h2>{{post.title}}</h2>
      <div innerHtml="{{post.content}}">
      </div>
      <!--Comment section-->
      <div class="pt-8">
        <h3 class="mb-8">Comments</h3>
        <ul class="comment-list">
          <li class="comment" *ngFor="let c of post?.comments">
            <div class="vcard">
              <img class="avatar" src="/assets/images/person_1.jpg" alt="Image placeholder" />
            </div>
            <div class="comment-body">
              <h4>{{c.author.name}}</h4>
              <div class="comment-meta">{{c.creationDate | date: 'MMMM/dd/yyyy'}}</div>
              <p>{{c.comment}}</p>
              <p><a href="#" class="reply rounded">Reply</a></p>
            </div>
          </li>
        </ul>
      </div>
      <div class="not-authenticated" *ngIf="!authService.isAuthenticated()">
        <h4 class="mb-5">Please <a [routerLink]="['/signin']">log in</a> or <a [routerLink]="['/signup']">register</a> to post a comment</h4>
      </div>
      <div class="comment-form-wrap pt-6" *ngIf="authService.isAuthenticated()">
        <form class="p-5 bg-light" [formGroup]="form" (submit)="createComment()">
          <div class="form-group">
            <label htmlFor="message">Leave a comment</label>
            <textarea formControlName="comment" id="message" cols={30} rows={10} class="form-control"></textarea>
          </div>
          <div class="alert alert-danger" *ngIf="f.comment.touched && f.comment.errors?.required">
            This field is required
          </div>
          <div class="form-group">
            <input type="submit" defaultValue="Post Comment" class="btn btn-primary" />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
